### PR TITLE
FHB-916 Fix blank page in service list

### PR DESCRIPTION
**Pull request by Top-Cat**

### CODE REVIEW

**Review by tgohil-hippo — DISMISSED** [review]

**Review by AaronJY — DISMISSED** [review]

**Comment by AaronJY** [comment]
Just checking this should be going into main?

**Comment by Top-Cat** [comment]
> Just checking this should be going into main?

As this is fixing the release issue with delete services. Should it go into another release?

**Review by Zac-Digital — DISMISSED** [review]

**Comment by AaronJY** [comment]
> > Just checking this should be going into main?
> 
> As this is fixing the release issue with delete services. Should it go into another release?

It's appearing in this release: https://dfedigital.atlassian.net/projects/FHB/versions/10568/tab/release-report-all-issues so I guess the target branch needs to be updated to the delete release branch

**Comment by Top-Cat** [comment]
> > > Just checking this should be going into main?
> > 
> > 
> > As this is fixing the release issue with delete services. Should it go into another release?
> 
> It's appearing in this release: https://dfedigital.atlassian.net/projects/FHB/versions/10568/tab/release-report-all-issues so I guess the target branch needs to be updated to the delete release branch

But that's been merged into main

**Review by Zac-Digital — APPROVED** [review]

**Review by AaronJY — APPROVED** [review]

**Pull request merged**
